server:
  port: 10000

spring:
  application:
    name: dashscope-chat-example
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus-2025-01-25
