server:
  port: 10020

spring:
  application:
    name: chat-memory-example
  profiles:
    active: dev
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus-2025-01-25
    chat:
      memory:
        repository:
          jdbc:
            mysql:
              jdbc-url: jdbc:mysql://localhost:3306/chat_memory?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrl
              username: root
              password: 123456
              driver-class-name: com.mysql.cj.jdbc.Driver
              enabled: true
            postgres:
              jdbc-url: jdbc:postgresql://127.0.0.1:5432/db
              username: pgsql
              password: 123456
              driver-class-name: org.postgresql.Driver
              initialize-schema: true