spring:
  application:
    name: rag-pgvector

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/db
    username: pgsql
    password: 123456

  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
    vectorstore:
      pgvector:
        dimensions: 1536
        index-type: hnsw
        distance-type: cosine_distance
        initialize-schema: true
server:
  port: 10011
