spring:
  application:
    name: rag-pgvector

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/db
    username: pgsql
    password: 123456

  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 1024
      chat:
        options:
          model: qwen-plus-2025-01-25
          temperature: 0.7
    vectorstore:
      pgvector:
        dimensions: 1024
        index-type: hnsw
        table-name: mxy_rag_vector
        initialize-schema: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 10011
