server:
  port: 10016

spring:
  application:
    name: rag-etl
  profiles:
    active: dev
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus-2025-01-25
