server:
  port: 10001

spring:
  application:
    name: deepseek-chat-example
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat