server:
  port: 10012

spring:
  application:
    name: flight-booking-agent
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus-2025-01-25
      embedding:
        options:
          model: text-embedding-v4
#        base-url: https://dashscope.aliyuncs.com/api/v1/services/embeddings/multimodal-embedding/multimodal-embedding
#    model:
#      embedding:
#        multimodal: multimodal-embedding-v1