server:
  port: 10010

spring:
  application:
    name: tool-calling-example
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
    vectorstore:
      milvus:
        client:
          host: 192.168.3.23
          port: 19530
        databaseName: "default"
        collectionName: "test_vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE
        initialize-schema: true