server:
  port: 10017

spring:
  application:
    name: nacos-prompt
  profiles:
    active: dev
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus-2025-01-25
    nacos:
      prompt:
        template:
          enabled: true
  nacos:
    server-addr: 127.0.0.1:8848
    