server:
  port: 10013

spring:
  application:
    name: spring-ai-observability-dashscope
  ai:
    dashscope:
      chat:
        options:
          model: qwen-plus-2025-01-25
      api-key: ${DASH_SCOPE_API_KEY}
      observations:
        log-completion: true
        log-prompt: true
      embedding:
        options:
          model: text-embedding-v4
    chat:
      client:
        observations:
          # default value is false.
          log-prompt: true
          log-completion: true
          include-error-logging: true
    # vector store config items
    vectorstore:
      observations:
        log-query-response: true

    # tools config items
    tools:
      observations:
        # default value is false.
        include-content: true

    # Image observation is only support openai for spring ai.
    # image:
    #   observations:
    #     log-prompt: true

  http:
    client:
      read-timeout: 60s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      # 应用健康状态检查，携带详细新学年
      show-details: always
  tracing:
    sampling:
      # trace 采样信息，记录每个请求
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://192.168.1.11:9411/api/v2/spans

